---
ctp_config:
    # ä¸ºç©ºæ—¶ä¸ç™»å½•
    ctp_front: ''
    ctp_front: 'sim_now'
    investor: ''
    password: ''
    product_info: ''
    app_id: ''
    auth_code: ''

    # è¿½å•è®¾ç½®
    chasing:
        wait_seconds: 3
        offset_ticks: -2
        resend_times: 3
    # ctpå‰ç½®é…ç½®: è¯·æ”¹ç”¨æœŸè´§å…¬å¸å¯¹åº.3.15(SE)çš„å‰ç½
    fronts:
        sim_now:
            trade: tcp://180.168.146.187:13030
            quote: tcp://180.168.146.187:14040
            broker: '9999'
# æ•°æ®æº- zmqé…ç½®
zmq_config: tcp://broadcast.eicp.net:55881
# å¼€å…
onoff:
    # æ˜¯å¦7*24
    running_as_server: true
    # æ˜¯å¦å‘é€å§”æ‰
    real_order_enable: true
    # ä¸€æ ¹Kçº¿åªå‘é€ä¸€æ¬¡æŒ‡ä»
    single_order_one_bar: true
    # æ˜¯å¦æ‰“å°è¡Œæƒ…æ—¶é—´
    show_tick_time: false
# ç­–ç•¥è·¯å¾„é…ç½®
stra_path:
    # è·¯å¾„
    strategies:
        # ç­–ç•¥æ–‡ä»¶å
        SMACross:
        # ç­–ç•¥é…ç½®å‚æ•°ID
        - 119
